# Generated by Django 5.0.1 on 2024-01-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
